# .project metadata for Kuasar
# Documentation: https://github.com/cncf/automation/tree/main/utilities/dot-project

# TODO: Add package_managers if distributed via registries

schema_version: "1.0.0"
slug: "kuasar"
name: "Kuasar"
description: "A multi-sandbox container runtime that provides cloud-native, all-scenario multiple sandbox container solutions."
type: "project"
project_lead: "Vanient" # TODO: AUTO-DETECTED — please verify
slack_channels: # TODO: AUTO-DETECTED — please verify the channel(s) below
  - name: "#kuasar"
    link: "https://slack.cncf.io/"
    primary: true

maturity_log:
  - phase: "sandbox"
    date: "2023-12-19T00:00:00Z"
    issue: "https://github.com/cncf/sandbox/issues/146" # TODO: AUTO-DETECTED — please verify

repositories:
  - "https://github.com/kuasar-io/kuasar"

website: "https://kuasar.io/"

artwork: "https://landscape.cncf.io/logos/kuasar.svg"

adopters:
  path: "https://github.com/kuasar-io/kuasar/blob/main/ADOPTERS.md"


# TODO: Add package manager identifiers if your project is distributed via registries
# package_managers:
#   docker: "kuasar-io/kuasar"

social:
  twitter: "https://twitter.com/Kuasar_io"

security:
  policy:
    path: "https://github.com/kuasar-io/kuasar/blob/main/SECURITY.md"
  contact:
    advisory_url: "https://github.com/kuasar-io/kuasar/security/advisories/new"

governance:
  contributing:
    path: "https://github.com/kuasar-io/kuasar/blob/main/CONTRIBUTING.md"
  code_of_conduct:
    path: "https://github.com/kuasar-io/kuasar/blob/main/CODE_OF_CONDUCT.md"

legal:
  license:
    path: "https://github.com/kuasar-io/kuasar/blob/main/LICENSE"
  identity_type:
    has_dco: true # AUTO-DETECTED — please verify
    has_cla: false # AUTO-DETECTED — please verify
    dco_url:
      path: "https://developercertificate.org/"

documentation:
  readme:
    path: "https://github.com/kuasar-io/kuasar/blob/main/README.md"

landscape:
  category: "Runtime"
  subcategory: "Container Runtime"

# CLOMonitor Score: 79/100
# Documentation: 90 | License: 100 | Best Practices: 42 | Security: 55
